---
- name: Remove logs from the previous installation
  hosts: openstack-client
  user: vagrant
  become: true

  tasks:
  - name: Remove older log files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/vagrant/logs/setup-hosts.log"
      - "/vagrant/logs/setup-hosts-fallback.log"
      - "/vagrant/logs/setup-infrastructure.log"
      - "/vagrant/logs/setup-infrastructure-fallback.log"
      - "/vagrant/logs/setup-openstack.log"
      - "/vagrant/logs/setup-openstack-fallback.log"

- name: Prep VMs for OpenStack
  hosts: all
  vars_files:
    - config.yml
  user: vagrant
  become: true

  roles:
    - prereqs
    - upgrade
    - networking
    - pip

- name: Run OpenStack Installation
  hosts: controller-01
  vars_files:
    - config.yml
  user: vagrant
  become: true

  vars:
    ansible_verbosity: "-v"

  roles:
    - getplaybooks
    - installansible
    - configuredeployment
    - runplaybooks

- name: Reload libvirtd
  hosts: compute-01
  user: vagrant
  become: true

  tasks:
    - name: Restart libvirtd at compute nodes
      service:
        name: libvirtd
        state: restarted

